atoms:
  number: 20
  mass: 1
  radius: 0.5
  max_velocity: 100
area:
  height: 50
  width: 20
gravity: 1
time_factor: 10
collision_tolerance: 0.05
detector:
  heightMultiplier: 5
  position: 30
duration:
  units: 20
