atoms:
  number: 20
  mass: 1
  radius: 0.5
  max_velocity: 100
area:
  height: 50
  width: 20
gravity: 1
time_factor: 10
ticks_per_frame: 10
collision_tolerance: 0.05
detector:
  height_multiplier: 10
  position: 30
  detection_delay: 200
duration:
  units: 20
